let shopItemData = [
  {
    id: "a",
    img: "./Images/catalog1.png",
    title: "Clerical GOODS",
    text: "10.00 $",
    cartImg: "./Images/cart.png",
  },
  {
    id: "b",
    img: "./Images/catalog2.png",
    title: "Clerical GOODS",
    text: "10.00 $",
    cartImg: "./Images/cart.png",
  },
  {
    id: "c",
    img: "./Images/catalog3.png",
    title: "Clerical GOODS",
    text: "10.00 $",
    cartImg: "./Images/cart.png",
  },
  {
    id: "d",
    img: "./Images/catalog4.png",
    title: "Clerical GOODS",
    text: "10.00 $",
    cartImg: "./Images/cart.png",
  },
  {
    id: "e",
    img: "./Images/catalog5.png",
    title: "Clerical GOODS",
    text: "10.00 $",
    cartImg: "./Images/cart.png",
  },
  {
    id: "f",
    img: "./Images/catalog6.png",
    title: "Clerical GOODS",
    text: "10.00 $",
    cartImg: "./Images/cart.png",
  },
  {
    id: "g",
    img: "./Images/catalog7.png",
    title: "Clerical GOODS",
    text: "10.00 $",
    cartImg: "./Images/cart.png",
  },
  {
    id: "h",
    img: "./Images/catalog8.png",
    title: "Clerical GOODS",
    text: "10.00 $",
    cartImg: "./Images/cart.png",
  },
  {
    id: "i",
    img: "./Images/catalog9.png",
    title: "Clerical GOODS",
    text: "10.00 $",
    cartImg: "./Images/cart.png",
  },
  {
    id: "j",
    img: "./Images/catalog10.png",
    title: "Clerical GOODS",
    text: "10.00 $",
    cartImg: "./Images/cart.png",
  },
  {
    id: "k",
    img: "./Images/catalog11.png",
    title: "Clerical GOODS",
    text: "10.00 $",
    cartImg: "./Images/cart.png",
  },
  {
    id: "l",
    img: "./Images/catalog1.png",
    title: "Clerical GOODS",
    text: "10.00 $",
    cartImg: "./Images/cart.png",
  },
];
