let shopItemData = [
  {
    id: "a",
    img: "./Images/catalog1.png",
    title: "Clerical GOODS",
    text: 10,
    cartImg: "./Images/cart.png",
    shippingPrice: 15,
    price: 2160,
  },
  {
    id: "b",
    img: "./Images/catalog2.png",
    title: "Clerical GOODS",
    text: 10,
    cartImg: "./Images/cart.png",
    shippingPrice: 15,
    price: 2160,
  },
  {
    id: "c",
    img: "./Images/catalog3.png",
    title: "Clerical GOODS",
    text: 10,
    cartImg: "./Images/cart.png",
    shippingPrice: 15,
    price: 2160,
  },
  {
    id: "d",
    img: "./Images/catalog4.png",
    title: "Clerical GOODS",
    text: 10,
    cartImg: "./Images/cart.png",
    shippingPrice: 15,
    price: 2160,
  },
  {
    id: "e",
    img: "./Images/catalog5.png",
    title: "Clerical GOODS",
    text: 10,
    cartImg: "./Images/cart.png",
    shippingPrice: 15,
    price: 2160,
  },
  {
    id: "f",
    img: "./Images/catalog6.png",
    title: "Clerical GOODS",
    text: 10,
    cartImg: "./Images/cart.png",
    shippingPrice: 15,
    price: 2160,
  },
  {
    id: "g",
    img: "./Images/catalog7.png",
    title: "Clerical GOODS",
    text: 10,
    cartImg: "./Images/cart.png",
    shippingPrice: 15,
    price: 2160,
  },
  {
    id: "h",
    img: "./Images/catalog8.png",
    title: "Clerical GOODS",
    text: 10,
    cartImg: "./Images/cart.png",
    shippingPrice: 15,
    price: 2160,
  },
  {
    id: "i",
    img: "./Images/catalog9.png",
    title: "Clerical GOODS",
    text: 10,
    cartImg: "./Images/cart.png",
    shippingPrice: 15,
    price: 2160,
  },
  {
    id: "j",
    img: "./Images/catalog10.png",
    title: "Clerical GOODS",
    text: 10,
    cartImg: "./Images/cart.png",
    shippingPrice: 15,
    price: 2160,
  },
  {
    id: "k",
    img: "./Images/catalog11.png",
    title: "Clerical GOODS",
    text: 10,
    cartImg: "./Images/cart.png",
    shippingPrice: 15,
    price: 2160,
  },
  {
    id: "l",
    img: "./Images/catalog1.png",
    title: "Clerical GOODS",
    text: 10,
    cartImg: "./Images/cart.png",
    shippingPrice: 15,
    price: 2160,
  },
];
